type Password{
    password: String!
    service: String!
    description: String!
}

input PasswordCreate{
    password: String!
    service: String!
    description: String!
}

type Query{
    getPassword: [Password!]!
    getPasswordByService(service: String!): Password
    getPasswordById(id: ID!): Password 
}

type Mutation{
    passwordCreate(input: PasswordCreate!): Password!
    passwordMake (input: PasswordCreate!): Password!
}